# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ec499a9d28e94285238137245fe2a3d717e7610f465f1b7cfce80d0ca1ea25a7500391d680b048ce472d80695a9ef6213efc43fd355e3b1ef3e847505c8944

test:
  secret_key_base: ea604efa69d3d65b0e3476a3f2abfbacb1f8784c24945626dcd05ea88bce0b09156fe5e05b3f14985ec08f6cb8690744bd63fa81f290c615136d6ee80d2afd23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
